### ISSUE TITLE
Like with wildcard not supported

### ISSUE THREAD

**Issue by xwan010** [sadikovi/spark-netflow#21]
A) Issue logs:
scala> sqlContext.sql("""select \* from episodes where srcip like "%9" """).show
16/03/17 11:23:46 INFO NetFlowRelation: Reduced filter: Some(StringEndsWith(srcip,9))
16/03/17 11:23:46 INFO NetFlowRelation: Resolved NetFlow filter: Some(TrivialPredicate(false))
16/03/17 11:23:46 INFO NetFlowFileRDD:
 NetFlow: {
   File: file:/c:/Projects/Netflow/spark-netflow/src/test/resources/correct/ftv5.2016-01-13.nocompress.bigend.sample,
   File length: 64048 bytes,
   Flow version: 5,
   Compression: false,
   Buffer size: 3698688 bytes,
   Start capture: 0,
   End capture: 0,
   Hostname: flow-gen,
   Comments: flow-gen
 }

16/03/17 11:23:46 DEBUG ScanPlanner: Predicate after update: TrivialPredicate(false)
16/03/17 11:23:46 DEBUG ScanPlanner: Strategy chosen: Strategy [SkipScan]
16/03/17 11:23:46 INFO NetFlowReader: Skip scan based on strategy Strategy [SkipScan]
+---------+----------+---------+------+-----+-----+-------+-----+------+-------+------+----------+---------+-------+-------+--------+---+---------+-----------+---------+--------+--------+------+------+
|unix_secs|unix_nsecs|sysuptime|exaddr|srcip|dstip|nexthop|input|output|packets|octets|first_flow|last_flow|srcport|dstport|protocol|tos|tcp_flags|engine_type|engine_id|src_mask|dst_mask|src_as|dst_as|
+---------+----------+---------+------+-----+-----+-------+-----+------+-------+------+----------+---------+-------+-------+--------+---+---------+-----------+---------+--------+--------+------+------+
+---------+----------+---------+------+-----+-----+-------+-----+------+-------+------+----------+---------+-------+-------+--------+---+---------+-----------+---------+--------+--------+------+------+

B) LIKE works fine without wildcard.
scala> sqlContext.sql("""select \* from episodes where srcip like "0.0.0.9" """).show
16/03/17 11:26:11 INFO NetFlowRelation: Reduced filter: Some(EqualTo(srcip,0.0.0.9))
16/03/17 11:26:11 INFO NetFlowRelation: Resolved NetFlow filter: Some(Eq(Column(srcip)[Long][16], 9))
16/03/17 11:26:11 INFO NetFlowFileRDD:
 NetFlow: {
   File: file:/c:/Projects/Netflow/spark-netflow/src/test/resources/correct/ftv5.2016-01-13.nocompress.bigend.sample,
   File length: 64048 bytes,
   Flow version: 5,
   Compression: false,
   Buffer size: 3698688 bytes,
   Start capture: 0,
   End capture: 0,
   Hostname: flow-gen,
   Comments: flow-gen
 }

16/03/17 11:26:11 DEBUG ScanPlanner: Predicate after update: Eq(Column(srcip)[Long][16], 9)
16/03/17 11:26:11 DEBUG ScanPlanner: Strategy chosen: Strategy [FilterScan]
16/03/17 11:26:11 INFO NetFlowReader: Filter scan based on strategy Strategy [FilterScan]
+---------+----------+---------+-------+-------+-----------+-------+-----+------+-------+------+----------+----------+-------+-------+--------+---+---------+-----------+---------+--------+--------+------+------+
|unix_secs|unix_nsecs|sysuptime| exaddr|  srcip|      dstip|nexthop|input|output|packets|octets|first_flow| last_flow|srcport|dstport|protocol|tos|tcp_flags|engine_type|engine_id|src_mask|dst_mask|src_as|dst_as|
+---------+----------+---------+-------+-------+-----------+-------+-----+------+-------+------+----------+----------+-------+-------+--------+---+---------+-----------+---------+--------+--------+------+------+
|        0|         0|        0|0.0.0.0|0.0.0.9|255.255.0.9|0.0.0.0|    9| 65289|     10|    10|         9|4294901769|      9|  65289|     UDP|  9|        0|          0|        0|       0|       0|     9| 65289|
+---------+----------+---------+-------+-------+-----------+-------+-----+------+-------+------+----------+----------+-------+-------+--------+---+---------+-----------+---------+--------+--------+------+------+

C)FYI: The script to create table.

> sqlContext.sql("""CREATE TEMPORARY TABLE episodes USING com.github.sadikovi.spark.netflow OPTIONS (path "file:///c:/Projects/Netflow/spark-netflow/src/test/resources/correct/ftv5.2016-01-13.nocompress.bigend.sample", version "5") """)

**Comment by sadikovi** [comment]
Wild cards are currently not supported for string columns, e.g. you cannot do this `srcip like %.100.12.%`. The full `like` predicate works because it is converted into equality, which is supported, you can also see it in logs. But yes, I agree, it would be cool, if wild cards worked with columns. 

I will fix it for `0.2.2` release.

**Comment by sadikovi** [comment]
Thanks for script with `CREATE TEMPORARY TABLE`, I will add it to `README`!

**Comment by sadikovi** [comment]
Fixed in a4db6c292097012511f2790e7b7a30f7727f9547. Now filters that are not supported will result in full scan, and Spark will do proper filtering.
