### ISSUE TITLE
Add support for Spark 2.x

### ISSUE THREAD

**Issue by sadikovi** [sadikovi/spark-netflow#56]

**Comment by shad197** [comment]
Any time line when Spark 2.x support will be added?

Thanks

**Comment by sadikovi** [comment]
Hi!

I am planning to create PR by the end of this month.

Currently considering to drop partitioning mode that exists in releases for
1.x.. I have not been using them very often, and not sure if other people
are using it.

**Comment by shad197** [comment]
Awesome! I'll be on the lookout for it.

Thanks!

**Comment by sadikovi** [comment]
@shad197 spark-netflow 2.0.0 is available on spark-packages and in master branch with support for Spark 2.x.

**Comment by shad197** [comment]
Thank you @sadikovi !!
