### ISSUE TITLE
Spark 3.0 support

### ISSUE THREAD

**Issue by alexott** [sadikovi/spark-netflow#79]
Spark 3.0 was released this year with a lot of optimizations, and improvements.  But the code isn't compiled out of the box due of the internal changes in the Spark, etc.   The amount of changes is relatively small although, and I have [them in my fork](https://github.com/alexott/spark-netflow/tree/spark-3.0). (Unfortunately, because of the problems with `sbt` and expired certificates, I was compiled the code using Maven instead).

P.S. I have branch for [2.4 as well](https://github.com/alexott/spark-netflow/tree/spark-2.4), but there changes aren't so big.

**Comment by sadikovi** [comment]
Thanks for reporting the issue. That's right, the package would need to be fixed for Spark 3.0. I will update the code based on your changes!

**Comment by sadikovi** [comment]
2.1.0 version is available with Spark 3.0.x support, see https://spark-packages.org/package/sadikovi/spark-netflow.
